### ISSUE TITLE
Import error on the Nuxt module

### ISSUE THREAD

**Issue by SlamaFR** [le-pepe/snow-effect#2]
Hi!

I might be wrong, but it looks like the Nuxt plugin for snow-effect is broken as I'm getting the following error:
```
[plugin:vite:import-analysis] Failed to resolve import "snow-effect/loader" from "node_modules/.pnpm/@le-pepe+nuxt-snow-effect@1.2.0_magicast@0.3.5_rollup@4.29.1/node_modules/@le-pepe/nuxt-snow-effect/dist/runtime/plugin.client.js?v=ec301a17". Does the file exist?
```

I think it should be `@le-pepe/snow-effect/loader` instead of `snow-effect/loader`?

I somehow managed to bypass this issue by creating a custom Nuxt plugin based on yours, but I think I'm missing the custom element definition as it is working on dev, but not in production.

**Comment by le-pepe** [comment]
> Hi!
> 
> I might be wrong, but it looks like the Nuxt plugin for snow-effect is broken as I'm getting the following error:
> 
> ```
> [plugin:vite:import-analysis] Failed to resolve import "snow-effect/loader" from "node_modules/.pnpm/@le-pepe+nuxt-snow-effect@1.2.0_magicast@0.3.5_rollup@4.29.1/node_modules/@le-pepe/nuxt-snow-effect/dist/runtime/plugin.client.js?v=ec301a17". Does the file exist?
> ```
> 
> I think it should be `@le-pepe/snow-effect/loader` instead of `snow-effect/loader`?
> 
> I somehow managed to bypass this issue by creating a custom Nuxt plugin based on yours, but I think I'm missing the custom element definition as it is working on dev, but not in production.

Hi, thank you for mentioning that there was an issue with the module. It has already been fixed. I would recommend reporting any bugs or issues with the module in its repository.
